#! /usr/bin/env node

const Utils = require('./lib/utils');

class Manager {
    constructor() {
        this.utils = new Utils(this);
        this.args = this.utils.args();
        console.log('emanator management utility');

        if(this.args.purge) {
//            let folder = path.join(os.homedir(),'emanator')
        }
    }
}

const manager = new Manager();
